/*
 * COPYRIGHT (C) 2017 NEC CORPORATION
 *
 * ALL RIGHTS RESERVED BY NEC CORPORATION,  THIS PROGRAM
 * MUST BE USED SOLELY FOR THE PURPOSE FOR WHICH IT WAS
 * FURNISHED BY NEC CORPORATION,  NO PART OF THIS PROGRAM
 * MAY BE REPRODUCED OR DISCLOSED TO OTHERS,  IN ANY FORM
 * WITHOUT THE PRIOR WRITTEN PERMISSION OF NEC CORPORATION.
 *
 * NEC CONFIDENTIAL AND PROPRIETARY
 */

#ifndef NECBAAS_NBHTTPREQUESTMETHOD_H
#define NECBAAS_NBHTTPREQUESTMETHOD_H

namespace necbaas {

/**
 * HTTPリクエストメソッド.
 */
enum class NbHttpRequestMethod {
    HTTP_REQUEST_TYPE_GET,    /*!< GET    */
    HTTP_REQUEST_TYPE_POST,   /*!< POST   */
    HTTP_REQUEST_TYPE_PUT,    /*!< PUT    */
    HTTP_REQUEST_TYPE_DELETE, /*!< DELETE */
};
}  // namespace necbaas

#endif  // NECBAAS_NBHTTPREQUESTMETHOD_H
